name: deploy-main

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_API }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_API }}:latest

      - name: Build & push Worker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.worker
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_WORKER }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_WORKER }}:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform init (S3 backend)
        working-directory: infra/terraform
        run: >
          terraform init
          -backend-config="bucket=${{ secrets.TFSTATE_BUCKET }}"
          -backend-config="key=${{ secrets.TFSTATE_KEY }}"
          -backend-config="region=${{ secrets.AWS_REGION }}"
          -backend-config="dynamodb_table=${{ secrets.TFSTATE_DYNAMODB_TABLE }}"
          -backend-config="encrypt=true"

      - name: Terraform apply
        working-directory: infra/terraform
        env:
          TF_VAR_project: ${{ secrets.TF_PROJECT }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_vpc_id: ${{ secrets.TF_VPC_ID }}
          TF_VAR_public_subnet_ids: ${{ secrets.TF_PUBLIC_SUBNET_IDS }}
          TF_VAR_private_subnet_ids: ${{ secrets.TF_PRIVATE_SUBNET_IDS }}
          TF_VAR_api_image: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_API }}:${{ github.sha }}
          TF_VAR_worker_image: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_WORKER }}:${{ github.sha }}
          TF_VAR_jwt_secret_key: ${{ secrets.TF_JWT_SECRET_KEY }}
          TF_VAR_db_password: ${{ secrets.TF_DB_PASSWORD }}
        run: terraform apply -auto-approve


